/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eweather.guiMenu;

import javax.swing.JOptionPane;

/**
 *
 * @author nikolas
 */
public class WeatherForecast extends javax.swing.JFrame {

    
    /**
     * Creates new form WeatherForecast
     */
    public WeatherForecast() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        citiesC = new javax.swing.JComboBox<>();
        forecast1 = new javax.swing.JButton();
        forecastUp = new javax.swing.JButton();
        returnBtn = new javax.swing.JButton();
        forekast5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        start = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        athensp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        thessalp = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        patrap = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        larisap = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        irakliop = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eWeather- Everywere you go always take the weather with you");
        setBounds(new java.awt.Rectangle(400, 280, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Πρόβλεψη Καιρού");

        jLabel2.setBackground(new java.awt.Color(204, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("επιλέξτε πόλη:");

        citiesC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Επιλέξτε πόλη>", "Αθήνα", "Θεσσαλονίκη", "Πάτρα", "Λάρισα", "Ηράκλειο" }));
        citiesC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                citiesCMouseClicked(evt);
            }
        });
        citiesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citiesCActionPerformed(evt);
            }
        });

        forecast1.setBackground(new java.awt.Color(102, 204, 255));
        forecast1.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        forecast1.setText("Πρόβλεψη καιρού μιας μέρας");
        forecast1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forecast1ActionPerformed(evt);
            }
        });

        forecastUp.setBackground(new java.awt.Color(102, 204, 255));
        forecastUp.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        forecastUp.setText("Ανανέωση προβλέψεων");
        forecastUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forecastUpActionPerformed(evt);
            }
        });

        returnBtn.setBackground(new java.awt.Color(237, 217, 47));
        returnBtn.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        returnBtn.setText("Επιστροφή στο αρχικό μενού");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        forekast5.setBackground(new java.awt.Color(102, 204, 255));
        forekast5.setFont(new java.awt.Font("Arial Black", 2, 12)); // NOI18N
        forekast5.setText("Πρόβλεψη καιρού 5 ημερών ");
        forekast5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forekast5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(citiesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(forecast1)
                    .addComponent(forekast5)
                    .addComponent(forecastUp, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBtn)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(citiesC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(forecast1)
                .addGap(18, 18, 18)
                .addComponent(forekast5)
                .addGap(18, 18, 18)
                .addComponent(forecastUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(returnBtn)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/simple.jpg"))); // NOI18N

        javax.swing.GroupLayout startLayout = new javax.swing.GroupLayout(start);
        start.setLayout(startLayout);
        startLayout.setHorizontalGroup(
            startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        startLayout.setVerticalGroup(
            startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel2.add(start, "card2");

        athensp.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ΑΘΗΝΑ");
        athensp.add(jLabel3);
        jLabel3.setBounds(20, 20, 88, 42);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/athens.jpg"))); // NOI18N
        athensp.add(jLabel4);
        jLabel4.setBounds(0, 0, 460, 400);

        jPanel2.add(athensp, "card2");

        thessalp.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ΘΕΣΣΑΛΟΝΙΚΗ");
        thessalp.add(jLabel5);
        jLabel5.setBounds(270, 20, 168, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/thessaloniki.jpg"))); // NOI18N
        thessalp.add(jLabel6);
        jLabel6.setBounds(0, 0, 460, 400);

        jPanel2.add(thessalp, "card2");

        patrap.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("ΠΑΤΡΑ");
        patrap.add(jLabel7);
        jLabel7.setBounds(10, 10, 90, 27);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patra.jpeg"))); // NOI18N
        patrap.add(jLabel8);
        jLabel8.setBounds(0, 0, 460, 400);

        jPanel2.add(patrap, "card2");

        larisap.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 204));
        jLabel9.setText("ΛΑΡΙΣΑ");
        larisap.add(jLabel9);
        jLabel9.setBounds(10, 10, 90, 27);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/larisa.jpeg"))); // NOI18N
        larisap.add(jLabel10);
        jLabel10.setBounds(0, 0, 460, 400);

        jPanel2.add(larisap, "card2");

        irakliop.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ΗΡΑΚΛΕΙΟ");
        irakliop.add(jLabel11);
        jLabel11.setBounds(10, 10, 130, 27);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iraklio.jpeg"))); // NOI18N
        irakliop.add(jLabel12);
        jLabel12.setBounds(0, 0, 460, 400);

        jPanel2.add(irakliop, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void citiesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citiesCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citiesCActionPerformed

    private void forecast1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forecast1ActionPerformed
        switch (citiesC.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "Δεν έχετε επιλέξει καμία πόλη");
                break;
        /* patrap.setVisible(false);
        */
            case 1:
                start.setVisible(false);
                athensp.setVisible(true);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;
            case 2:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(true);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;
            case 3:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(true);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;    
            case 4:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(true);
                irakliop.setVisible(false);
                break; 
            case 5:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(true);
                break;    
            default:
                break;
        }                                    
    }//GEN-LAST:event_forecast1ActionPerformed

    private void forecastUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forecastUpActionPerformed
       switch (citiesC.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "Δεν έχετε επιλέξει καμία πόλη");
                break;
        /* patrap.setVisible(false);
        */
            case 1:
                start.setVisible(false);
                athensp.setVisible(true);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;
            case 2:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(true);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;
            case 3:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(true);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;    
            case 4:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(true);
                irakliop.setVisible(false);
                break; 
            case 5:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(true);
                break;    
            default:
                break;
        }                                   
    }//GEN-LAST:event_forecastUpActionPerformed

    private void forekast5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forekast5ActionPerformed
        switch (citiesC.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "Δεν έχετε επιλέξει καμία πόλη");
                break;
        /* patrap.setVisible(false);
        */
            case 1:
                start.setVisible(false);
                athensp.setVisible(true);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;
            case 2:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(true);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;
            case 3:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(true);
                larisap.setVisible(false);
                irakliop.setVisible(false);
                break;    
            case 4:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(true);
                irakliop.setVisible(false);
                break; 
            case 5:
                start.setVisible(false);
                athensp.setVisible(false);
                thessalp.setVisible(false);
                patrap.setVisible(false);
                larisap.setVisible(false);
                irakliop.setVisible(true);
                break;    
            default:
                break;
        }
        
    }//GEN-LAST:event_forekast5ActionPerformed

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        this.hide();
        new Menu().setVisible(true);
    }//GEN-LAST:event_returnBtnActionPerformed

    private void citiesCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_citiesCMouseClicked
      // TODO add your handling code here:
    }//GEN-LAST:event_citiesCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherForecast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherForecast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherForecast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherForecast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherForecast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel athensp;
    private javax.swing.JComboBox<String> citiesC;
    private javax.swing.JButton forecast1;
    private javax.swing.JButton forecastUp;
    private javax.swing.JButton forekast5;
    private javax.swing.JPanel irakliop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel larisap;
    private javax.swing.JPanel patrap;
    private javax.swing.JButton returnBtn;
    private javax.swing.JPanel start;
    private javax.swing.JPanel thessalp;
    // End of variables declaration//GEN-END:variables
}